codecov:
  # Token per l'autenticazione, se necessario
  token: "${{ secrets.CODECOV_TOKEN }}"

  # Esclusioni
  exclude:
    - 'FinalProject/Database/Migrations/*'
    - '**/*Migration*'

  # Opzioni di reportistica
  comment: true
  coverage: true
