name: Build and Test

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest  

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Clean previous builds
        run: dotnet clean

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests with coverage
        run: dotnet test --collect:"XPlat Code Coverage" --results-directory TestResults

      - name: Publish artifacts
        if: success()
        run: |
          mkdir output
          for proj in $(find . -name '*.csproj'); do
            dotnet publish "$proj" -c Release -o output/$(basename "$proj" .csproj)
          done
          Compress-Archive -Path output/* -DestinationPath output.zip

      - name: Upload ZIP artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: output.zip

      - name: Upload coverage report to Codecov
        if: success()
        uses: codecov/codecov-action@v4
        with:
          token: eb0ae00f-cbbf-4d52-97d2-9c060117122f
          files: TestResults/**/*.xml
          flags: unittests
          name: code-coverage-report
